language: c++

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - cmake
      - cmake-data
      - libbullet-dev
      - freeglut3-dev
script:
  - git submodule init && git submodule update
  - mkdir build && cd build && cmake .. && make
