language: c++

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - kubuntu-backports
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - cmake
      - cmake-data
      - libbullet-dev
      - freeglut3-dev
      - libglu1-mesa-dev
      - libx11-dev
      - libxxf86vm-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
script:
  - git submodule init && git submodule update
  - mkdir build && cd build && cmake .. && make
